apiVersion: 1
policies:
    - orgId: 1
      receiver: teams-infra
      group_by:
        - grafana_folder
        - alertname
        - hostname
        - serverity
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
