spring:
  datasource:
    url: jdbc:h2:mem:spring-jpa-test-db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console.enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
  test.database.replace: none
