services:
  db:
    container_name: mariadb-dev
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./mysql/.env
    environment:
      TZ: Asia/Seoul
    restart: always
