- targets:
    - "192.168.xxx.xxx:9100"
  labels:
    role: "infra"
    env: "local"

- targets:
    - "192.168.xxx.xxx:9100"
  labels:
    role: "local-test"
    env: "local"

- targets:
    - "192.168.xxx.xxx:9100"
    ...
  labels:
    role: "k8s"
    env: "local"