global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ubuntu-node"
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/ubuntu-nodes.yml
        refresh_interval: 30s

  - job_name: "cadvisor"
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/cadvisor.yml
        refresh_interval: 30s
